name: scanpro
description: "All-in-One PDF Converter, Editor & Tools | Free Online."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  syncfusion_flutter_pdf: ^28.2.9
  syncfusion_flutter_pdfviewer: ^28.1.37

  camera: ^0.10.5+5
  image_picker: ^1.0.7
  image: ^4.1.6
  flutter_image_compress: ^2.1.0
  photo_view: ^0.15.0

  # Storage
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  google_fonts: ^6.1.0
  flutter_slidable: ^4.0.0
  shimmer: ^3.0.0
  flex_color_scheme: ^8.1.1

  # Utilities
  share_plus: ^10.1.4
  intl: ^0.19.0
  uuid: ^4.3.3
  permission_handler: ^11.3.0
  path: ^1.8.3
  mobile_scanner: ^6.0.7
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  barcode: ^2.2.9
  url_launcher: ^6.2.4
  local_auth: ^2.1.8
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.2
  reorderable_grid_view: ^2.2.8
  flutter_doc_scanner: ^0.0.16
  printing: ^5.14.2
  pro_image_editor: ^9.0.2
  flutter_screenutil: ^5.9.3
  open_file: ^3.5.10
  flutter_highlight: ^0.7.0
  http: ^1.3.0
  pdf_render:
    git:
      url: https://github.com/anjogithub/flutter_pdf_render.git
  flutter_svg: ^2.0.17
  animated_bottom_navigation_bar: ^1.4.0
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  super_tooltip: ^2.0.9
  go_router: ^14.8.1
  easy_localization: ^3.0.7+1
  logger: ^2.5.0
  mailer: ^6.4.1
  lottie: ^3.3.1
  purchases_flutter: ^8.6.1
  shared_preferences: ^2.5.2
  # google_sign_in: ^6.3.0
  # googleapis: ^14.0.0
  # extension_google_sign_in_as_googleapis_auth: ^2.0.12
  # archive: ^4.0.4
  # icloud_storage_sync: ^0.0.2
  # shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  macos:
    generate: true
    image_path: "assets/icons/ic_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/languages/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
