// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcaknOfl4ntt1twbrWInkmeYdtiSRMgh4',
    appId: '1:692883557073:web:399cb049e188c659ead3f0',
    messagingSenderId: '692883557073',
    projectId: 'scanpro-project',
    authDomain: 'scanpro-project.firebaseapp.com',
    storageBucket: 'scanpro-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN-sqgLFrssB9eTlyyuomWPzWwhNwpDeo',
    appId: '1:692883557073:android:9163b401e4d338c6ead3f0',
    messagingSenderId: '692883557073',
    projectId: 'scanpro-project',
    storageBucket: 'scanpro-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAusi-n22ZwEJcTWlKbEK9ImP-xeJ4OA6o',
    appId: '1:692883557073:ios:333afbc01e40601eead3f0',
    messagingSenderId: '692883557073',
    projectId: 'scanpro-project',
    storageBucket: 'scanpro-project.firebasestorage.app',
    iosBundleId: 'com.scanpro.documentconverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAusi-n22ZwEJcTWlKbEK9ImP-xeJ4OA6o',
    appId: '1:692883557073:ios:500ede779d83d93aead3f0',
    messagingSenderId: '692883557073',
    projectId: 'scanpro-project',
    storageBucket: 'scanpro-project.firebasestorage.app',
    iosBundleId: 'com.example.easyScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcaknOfl4ntt1twbrWInkmeYdtiSRMgh4',
    appId: '1:692883557073:web:fcfa3bf2d14ec708ead3f0',
    messagingSenderId: '692883557073',
    projectId: 'scanpro-project',
    authDomain: 'scanpro-project.firebaseapp.com',
    storageBucket: 'scanpro-project.firebasestorage.app',
  );
}
